force_multiline_blocks = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
newline_style = "Unix"
normalize_comments = true
reorder_impl_items = true
use_field_init_shorthand = true
