[package]
name = "vlogpp"
version = "0.1.0"
edition = "2024"

[dependencies]
delegate = "0.13.4"
indoc = "2.0.6"
ordermap = { version = "0.5.12", features = ["serde"] }
serde = { version = "1.0.228", features = ["serde_derive"] }
serde_json = "1.0.145"
