[package]
name = "vlogpp"
version = "0.1.0"
edition = "2024"

[dependencies]
indexmap = "2.11.4"
ordermap = { version = "0.5.12", features = ["serde"] }
serde = { version = "1.0.228", features = ["serde_derive"] }
serde_json = "1.0.145"
